services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret # Use strong password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    ports:
      - "80:80"  # Prod can use 80 on a server
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=laravel_db
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret # Use strong password
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: